algo1 = input('Digite algo: ')
print('Foi digitado: {}, e seu tipo primitivo é {}.'.format(algo1, type(algo1)))
print('Ele é número? ', algo1.isnumeric())
print('Ele é texto alfanumerico? ', algo1.isalnum())
print('Ele só tem espaços? ', algo1.isspace())
print('Ele é alfabetico? ', algo1.isalpha())
print('Ele está em maiuscula? ', algo1.isupper())
print('Ele está em minúscula? ', algo1.islower())
print('Ele está capitalizada? Em maiscula e minuscula? ', algo1.istitle())
