nome = str(input('Digite um nome: ')).strip()
print('Analisando seu nome...')
print('Nome em todas as letras maiusculas: {}!'.format(nome.upper()))
print('Nome em todas as letras minisculas: {}!'.format(nome.lower()))
tudojunto = ''.join(nome.split())
print('Total de {} letras, sem considerar espaços!'.format(len(tudojunto)))
print('Total de {} letras, sem considerar espaços!'.format(len(nome) - nome.count(' ')))
p_nome = nome.split()
print('Primeiro nome tem {} letras'.format(len(p_nome[0])))
print('Primeiro nome tem {} letras'.format(nome.find(' ')))
